# Generated by Django 4.2.8 on 2023-12-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arkafren',
            fields=[
                ('arkafrenid', models.AutoField(db_column='ArkaFrenID', primary_key=True, serialize=False)),
                ('arkafren', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='ArkaFren', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ArkaFren',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Turkish_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Turkish_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Turkish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Turkish_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Turkish_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Turkish_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Turkish_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Turkish_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Turkish_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Turkish_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Turkish_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Turkish_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Turkish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Turkish_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Turkish_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Turkish_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Turkish_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favoriler',
            fields=[
                ('favorilerid', models.AutoField(db_column='FavorilerID', primary_key=True, serialize=False)),
                ('olusturmatarihi', models.DateTimeField(blank=True, db_column='OlusturmaTarihi', null=True)),
                ('sonduzenleme', models.DateTimeField(blank=True, db_column='SonDuzenleme', null=True)),
                ('urunsayisi', models.IntegerField(blank=True, db_column='UrunSayisi', null=True)),
            ],
            options={
                'db_table': 'Favoriler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorilerdetay',
            fields=[
                ('favorilerdetayid', models.AutoField(db_column='FavorilerDetayID', primary_key=True, serialize=False)),
                ('tarih', models.DateTimeField(blank=True, db_column='Tarih', null=True)),
            ],
            options={
                'db_table': 'FavorilerDetay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiyat',
            fields=[
                ('fiyatid', models.AutoField(db_column='FiyatID', primary_key=True, serialize=False)),
                ('fiyatlink', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='FiyatLink', max_length=500, null=True)),
                ('fiyat', models.FloatField(blank=True, db_column='Fiyat', null=True)),
            ],
            options={
                'db_table': 'Fiyat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fiyatlar',
            fields=[
                ('fiyatlarid', models.AutoField(db_column='FiyatlarID', primary_key=True, serialize=False)),
                ('fiyatsayisi', models.IntegerField(blank=True, db_column='FiyatSayisi', null=True)),
                ('sitesayisi', models.IntegerField(blank=True, db_column='SiteSayisi', null=True)),
            ],
            options={
                'db_table': 'Fiyatlar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Frenteknolojisi',
            fields=[
                ('frenteknolojisiid', models.AutoField(db_column='FrenTeknolojisiID', primary_key=True, serialize=False)),
                ('frenteknolojisi', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='FrenTeknolojisi', max_length=50, null=True)),
            ],
            options={
                'db_table': 'FrenTeknolojisi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genelozellik',
            fields=[
                ('genelozellikid', models.AutoField(db_column='GenelOzellikID', primary_key=True, serialize=False)),
                ('motorgucumax', models.IntegerField(blank=True, db_column='MotorGucumax', null=True)),
                ('menzilmax', models.IntegerField(blank=True, db_column='Menzilmax', null=True)),
                ('hizmax', models.IntegerField(blank=True, db_column='Hizmax', null=True)),
                ('tasimakapasitesi', models.IntegerField(blank=True, db_column='TasimaKapasitesi', null=True)),
                ('tekerleksayisi', models.IntegerField(blank=True, db_column='TekerlekSayisi', null=True)),
                ('lastikebati', models.IntegerField(blank=True, db_column='LastikEbati', null=True)),
                ('katlanabilme', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Katlanabilme', max_length=5, null=True)),
            ],
            options={
                'db_table': 'GenelOzellik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Korumasertifikasyonu',
            fields=[
                ('korumasertifikasyonuid', models.AutoField(db_column='KorumaSertifikasyonuID', primary_key=True, serialize=False)),
                ('korumasertifikasyonu', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='KorumaSertifikasyonu', max_length=100, null=True)),
            ],
            options={
                'db_table': 'KorumaSertifikasyonu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('kullaniciid', models.AutoField(db_column='KullaniciID', primary_key=True, serialize=False)),
                ('kullaniciadi', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='KullaniciAdi', max_length=50, null=True)),
                ('sifre', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Sifre', max_length=50, null=True)),
                ('isimsoyisim', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='IsimSoyisim', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Email', max_length=100, null=True)),
                ('cinsiyet', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Cinsiyet', max_length=1, null=True)),
                ('olusturmatarihi', models.DateTimeField(blank=True, db_column='OlusturmaTarihi', null=True)),
                ('dogumgunu', models.DateField(blank=True, db_column='Dogumgunu', null=True)),
                ('tel', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Tel', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Kullanici',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('markaid', models.AutoField(db_column='MarkaID', primary_key=True, serialize=False)),
                ('marka', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Marka', max_length=100, null=True)),
                ('markalink', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='MarkaLink', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Marka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('modelid', models.AutoField(db_column='ModelID', primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Model', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Onfren',
            fields=[
                ('onfrenid', models.AutoField(db_column='OnFrenID', primary_key=True, serialize=False)),
                ('onfren', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Onfren', max_length=50, null=True)),
            ],
            options={
                'db_table': 'OnFren',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Renk',
            fields=[
                ('renkid', models.AutoField(db_column='RenkID', primary_key=True, serialize=False)),
                ('renk', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Renk', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Renk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Satici',
            fields=[
                ('saticiid', models.AutoField(db_column='SaticiID', primary_key=True, serialize=False)),
                ('satici', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Satici', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Satici',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('scooterid', models.AutoField(db_column='ScooterID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Scooter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('siteid', models.AutoField(db_column='SiteID', primary_key=True, serialize=False)),
                ('site', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Site', max_length=50, null=True)),
                ('sitelink', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='SiteLink', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Turkish_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tekerlektipi',
            fields=[
                ('tekerlektipiid', models.AutoField(db_column='TekerlekTipiID', primary_key=True, serialize=False)),
                ('tekerlektipi', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='TekerlekTipi', max_length=50, null=True)),
            ],
            options={
                'db_table': 'TekerlekTipi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teknikozellik',
            fields=[
                ('teknikozellikid', models.AutoField(db_column='TeknikOzellikID', primary_key=True, serialize=False)),
                ('bataryavoltaji', models.IntegerField(blank=True, db_column='BataryaVoltaji', null=True)),
                ('bataryaakimi', models.IntegerField(blank=True, db_column='BataryaAkimi', null=True)),
                ('tirmanmaacisi', models.IntegerField(blank=True, db_column='TirmanmaAcisi', null=True)),
                ('agirlik', models.FloatField(blank=True, db_column='Agirlik', null=True)),
            ],
            options={
                'db_table': 'TeknikOzellik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('urunid', models.AutoField(db_column='UrunID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Urun',
                'managed': False,
            },
        ),
    ]
